import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#FAF9FA' },
  scroll: {
    paddingHorizontal: 24,
    paddingTop: 8,
    paddingBottom: 24,
  },
  title: {
    fontSize: 28,
    fontWeight: '800',
    textAlign: 'center',
    marginVertical: 20,
  },
  card: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    padding: 20,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  label: {
    fontSize: 16,
    fontWeight: '500',
    marginTop: 6,
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ddd',
    backgroundColor: '#fff',
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 16,
  },
  sliderRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 6 },
  sliderHint: {
    fontSize: 15,
    color: '#444',
    marginRight: 6,
  },
  sliderValue: {
    fontSize: 18,
    fontWeight: '700',
    marginRight: 6,
  },
  slider: {
    marginHorizontal: 4,
  },
  scanButton: {
    marginTop: 10,
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#222',
  },
  scanButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#222',
  },
  inputDisabled: {
    backgroundColor: '#f1f1f1',
    color: '#777',
  },
  actionsRow: {
    marginTop: 22,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 12,
  },
  button: {
    backgroundColor: '#222',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  leaveButton: {
    backgroundColor: '#c1121f',
    borderRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  leaveButtonDisabled: {
    opacity: 0.6,
  },
  resultCard: {
    marginTop: 24,
    backgroundColor: '#f7f7f7',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#dedede',
    padding: 16,
  },
  resultText: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 6,
  },
  resultHint: {
    fontSize: 14,
    color: '#555',
  },
  dashboardCard: {
    marginTop: 16,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#dfe5fb',
    backgroundColor: '#f7f9ff',
    padding: 18,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
  },
  dashboardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 16,
    marginBottom: 12,
  },
  dashboardHeaderText: {
    flex: 1,
    gap: 4,
  },
  dashboardTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111',
  },
  dashboardSubtitle: {
    fontSize: 15,
    color: '#333',
  },
  dashboardConnection: {
    fontSize: 13,
    color: '#5f6b94',
  },
  queueStatsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#e0e5ff',
  },
  queueStat: {
    flex: 1,
    alignItems: 'center',
  },
  queueStatLabel: {
    fontSize: 13,
    color: '#57607a',
  },
  queueStatValue: {
    fontSize: 28,
    fontWeight: '700',
    color: '#0f172a',
    marginTop: 4,
  },
  queueStatDivider: {
    width: 1,
    height: 40,
    backgroundColor: '#e0e5ff',
  },
  presenceCard: {
    marginTop: 20,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e3e3e3',
    backgroundColor: '#fff',
    padding: 18,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 2 },
  },
  presenceTitle: {
    fontSize: 18,
    fontWeight: '700',
    marginBottom: 6,
  },
  presenceHint: {
    fontSize: 13,
    color: '#555',
    marginBottom: 4,
  },
  presenceDescription: {
    fontSize: 14,
    color: '#444',
    marginBottom: 12,
  },
  locationEnableButton: {
    borderWidth: 1,
    borderColor: '#1f6feb',
    borderRadius: 10,
    paddingVertical: 10,
    alignItems: 'center',
    marginBottom: 10,
  },
  locationEnableButtonActive: {
    backgroundColor: 'rgba(31,111,235,0.08)',
  },
  locationEnableText: {
    color: '#1f6feb',
    fontSize: 15,
    fontWeight: '600',
  },
  presenceStatus: {
    fontSize: 14,
    color: '#111',
  },
  declareButton: {
    marginTop: 12,
    backgroundColor: '#1f6feb',
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  declareButtonDisabled: {
    opacity: 0.4,
  },
  declareButtonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  presenceFootnote: {
    marginTop: 10,
    fontSize: 13,
    color: '#555',
  },
  timerCard: {
    marginTop: 20,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#d9e2ff',
    backgroundColor: '#f1f5ff',
    padding: 18,
    alignItems: 'center',
    gap: 8,
  },
  timerTitle: {
    fontSize: 18,
    fontWeight: '700',
  },
  timerHint: {
    fontSize: 13,
    color: '#444',
    textAlign: 'center',
  },
  queueCard: {
    marginTop: 20,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e7e7e7',
    backgroundColor: '#fff',
    padding: 16,
  },
  queueTitle: {
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 8,
  },
  queueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    gap: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  queueRowSelf: {
    backgroundColor: 'rgba(31,111,235,0.08)',
    borderRadius: 10,
    paddingHorizontal: 6,
  },
  queueRowCalled: {
    borderLeftWidth: 3,
    borderLeftColor: '#1f6feb',
    paddingLeft: 8,
  },
  queuePosition: {
    width: 28,
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
    color: '#1f1f1f',
  },
  queueRowInfo: {
    flex: 1,
  },
  queueRowName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111',
  },
  queueRowMeta: {
    fontSize: 13,
    color: '#555',
    marginTop: 2,
  },
  scannerContainer: {
    flex: 1,
    backgroundColor: '#000',
  },
  camera: {
    flex: 1,
  },
  scannerControls: {
    padding: 20,
    backgroundColor: '#111',
  },
  scannerHint: {
    color: '#f1f1f1',
    fontSize: 16,
    marginBottom: 12,
    textAlign: 'center',
  },
  scannerCloseButton: {
    alignSelf: 'center',
    paddingVertical: 10,
    paddingHorizontal: 28,
    borderRadius: 999,
    backgroundColor: '#f5f5f5',
  },
  scannerCloseText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#111',
  },
  webModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  webModalCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 16,
    backgroundColor: '#fff',
    padding: 20,
    gap: 16,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  webModalTitle: {
    fontSize: 19,
    fontWeight: '700',
    color: '#111',
  },
  webModalMessage: {
    fontSize: 15,
    color: '#444',
    lineHeight: 21,
  },
  webModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  webModalCancelButton: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    backgroundColor: '#f5f5f5',
  },
  webModalCancelText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#333',
  },
  webModalConfirmButton: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#c1121f',
  },
  webModalConfirmButtonDisabled: {
    opacity: 0.6,
  },
  webModalConfirmText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
  },
});
