import { StyleSheet } from 'react-native';

export default StyleSheet.create({
    safe: { flex: 1, backgroundColor: '#FAF9FA' },
    scroll: {
        paddingHorizontal: 24,
        paddingTop: 16,
        paddingBottom: 32,
    },
    title: {
        fontSize: 28,
        fontWeight: '800',
        textAlign: 'center',
        marginBottom: 8,
    },
    card: {
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#e6e6e6',
        padding: 20,
        backgroundColor: '#fff',
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 4 },
        elevation: 2,
        marginBottom: 18,
    },
    codeBadge: {
        alignSelf: 'flex-start',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 16,
        backgroundColor: '#F1F3F7',
        marginBottom: 12,
    },
    codeBadgeLabel: {
        fontSize: 12,
        textTransform: 'uppercase',
        fontWeight: '700',
        color: '#4a5568',
    },
    codeBadgeValue: {
        fontSize: 16,
        fontWeight: '700',
        color: '#111',
        letterSpacing: 1,
    },
    statusText: {
        fontSize: 20,
        fontWeight: '700',
        color: '#111',
        marginBottom: 6,
    },
    infoText: {
        fontSize: 15,
        color: '#444',
        marginBottom: 6,
    },
    connectionText: {
        fontSize: 13,
        color: '#586069',
    },
    calledText: {
        marginTop: 10,
        fontSize: 16,
        fontWeight: '700',
        color: '#0a7d34',
    },
    timerRow: {
        marginTop: 6,
    },
    pushButton: {
        marginTop: 16,
        alignSelf: 'flex-start',
        paddingHorizontal: 16,
        paddingVertical: 10,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#1f6feb',
    },
    pushButtonActive: {
        backgroundColor: '#1f6feb',
    },
    pushButtonText: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1f6feb',
    },
    pushButtonTextActive: {
        color: '#fff',
    },
    metaText: {
        marginTop: 8,
        fontSize: 13,
        color: '#586069',
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        marginBottom: 12,
        color: '#111',
    },
    metricsGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        gap: 12,
    },
    metricItem: {
        width: '48%',
        padding: 12,
        borderRadius: 12,
        backgroundColor: '#F7F8FB',
    },
    metricLabel: {
        fontSize: 13,
        color: '#4a4a4a',
        marginBottom: 4,
    },
    metricValue: {
        fontSize: 20,
        fontWeight: '700',
        color: '#111',
    },
    detailRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    detailLabel: {
        fontSize: 15,
        color: '#555',
    },
    detailValue: {
        fontSize: 16,
        fontWeight: '600',
        color: '#111',
    },
    actions: {
        marginTop: 8,
        alignItems: 'center',
    },
    leaveButton: {
        backgroundColor: '#c1121f',
        borderRadius: 14,
        paddingVertical: 14,
        paddingHorizontal: 24,
        alignItems: 'center',
        width: '100%',
    },
    leaveButtonDisabled: {
        opacity: 0.6,
    },
    leaveButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    secondaryButton: {
        backgroundColor: '#111',
        borderRadius: 14,
        paddingVertical: 14,
        paddingHorizontal: 24,
        alignItems: 'center',
        width: '100%',
    },
    secondaryButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    webModalBackdrop: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.4)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 24,
    },
    webModalCard: {
        width: '100%',
        maxWidth: 420,
        borderRadius: 16,
        backgroundColor: '#fff',
        padding: 20,
        gap: 16,
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 8 },
        elevation: 6,
    },
    webModalTitle: {
        fontSize: 19,
        fontWeight: '700',
        color: '#111',
    },
    webModalMessage: {
        fontSize: 15,
        color: '#444',
        lineHeight: 21,
    },
    webModalActions: {
        flexDirection: 'row',
        justifyContent: 'flex-end',
        gap: 12,
    },
    webModalCancelButton: {
        paddingHorizontal: 18,
        paddingVertical: 10,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#ccc',
        backgroundColor: '#f5f5f5',
    },
    webModalCancelText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#111',
    },
    webModalConfirmButton: {
        paddingHorizontal: 18,
        paddingVertical: 10,
        borderRadius: 10,
        backgroundColor: '#c1121f',
    },
    webModalConfirmButtonDisabled: {
        opacity: 0.6,
    },
    webModalConfirmText: {
        fontSize: 15,
        fontWeight: '600',
        color: '#fff',
    },
});
