import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#FAF9FA',
  },
  containerFixed: {
    flex: 1,
  },
  containerContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 32,
    gap: 16,
    flexGrow: 1,
  },
  mobileScroll: {
    flex: 1,
  },
  headerCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    padding: 18,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
    gap: 6,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
  },
  headerEvent: {
    fontSize: 17,
    fontWeight: '600',
    color: '#222',
  },
  headerLine: {
    fontSize: 15,
    color: '#444',
  },
  headerCodeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  headerCodeValue: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111',
  },
  headerCopyButton: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d0d0d0',
    backgroundColor: '#f5f5f5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCopyText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#222',
  },
  statusRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: 4,
  },
  statusBadge: {
    fontSize: 13,
    fontWeight: '600',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    overflow: 'hidden',
  },
  statusActive: {
    color: '#0f5132',
    backgroundColor: '#d1e7dd',
  },
  statusClosed: {
    color: '#842029',
    backgroundColor: '#f8d7da',
  },
  connectionText: {
    fontSize: 13,
    color: '#606060',
  },
  nowServingCard: {
    borderRadius: 14,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#dcdcdc',
    padding: 18,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
    gap: 8,
  },
  nowServingHeading: {
    fontSize: 18,
    fontWeight: '700',
  },
  nowServingValue: {
    fontSize: 16,
  },
  timerRow: {
    marginTop: 4,
  },
  timerHint: {
    marginTop: 6,
    fontSize: 13,
    color: '#666',
  },
  queueCard: {
    flexGrow: 1,
    minHeight: 160,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  queueList: {
    flex: 1,
    paddingVertical: 8,
  },
  queueItem: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    gap: 4,
  },
  queueItemLast: {
    borderBottomWidth: 0,
  },
  queueItemName: {
    fontSize: 16,
    fontWeight: '600',
  },
  queueItemMeta: {
    fontSize: 13,
    color: '#606060',
  },
  queueActionsRow: {
    flexDirection: 'row',
    gap: 12,
    paddingHorizontal: 20,
    paddingBottom: 12,
    paddingTop: 8,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: '#222',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonDisabled: {
    backgroundColor: '#999',
  },
  destructiveButton: {
    flex: 1,
    backgroundColor: '#c1121f',
    borderRadius: 10,
    paddingVertical: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '600',
  },
  queueItemButton: {
    marginTop: 8,
    alignSelf: 'flex-start',
    backgroundColor: '#1f6feb',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  queueItemButtonText: {
    color: '#fff',
    fontSize: 13,
    fontWeight: '600',
  },
  emptyState: {
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  emptyStateText: {
    fontSize: 14,
    color: '#777',
  },
  reconnectButton: {
    marginTop: 6,
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#bbb',
  },
  reconnectButtonText: {
    fontSize: 13,
    color: '#333',
    fontWeight: '600',
  },
  qrCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    backgroundColor: '#fefefe',
    padding: 20,
    alignItems: 'stretch',
    gap: 16,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  qrHeading: {
    fontSize: 18,
    fontWeight: '700',
    color: '#0f172a',
  },
  qrPoster: {
    marginTop: 4,
    borderRadius: 18,
    paddingHorizontal: 20,
    paddingVertical: 24,
    backgroundColor: '#ffffff',
    alignItems: 'center',
    gap: 14,
    borderWidth: 1,
    borderColor: '#f3f3f3',
    shadowColor: '#0f172a',
    shadowOpacity: 0.07,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 8 },
    elevation: 2,
  },
  qrPosterBadge: {
    fontSize: 12,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: '#4f46e5',
  },
  qrPosterTitle: {
    fontSize: 22,
    fontWeight: '800',
    color: '#0f172a',
    textAlign: 'center',
  },
  qrPosterSubtitle: {
    fontSize: 15,
    color: '#475467',
    textAlign: 'center',
  },
  qrCodeWrapper: {
    padding: 16,
    borderRadius: 16,
    backgroundColor: '#f4f6fb',
    borderWidth: 1,
    borderColor: '#e0e7ff',
  },
  qrHint: {
    fontSize: 13,
    color: '#606060',
    textAlign: 'center',
  },
  qrPosterCodeBlock: {
    width: '100%',
    padding: 14,
    borderRadius: 14,
    backgroundColor: '#0f172a',
    alignItems: 'center',
    gap: 2,
  },
  qrPosterCodeLabel: {
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 1,
    color: '#a5b4fc',
    fontWeight: '600',
  },
  qrPosterCodeValue: {
    fontSize: 26,
    fontWeight: '800',
    color: '#fff',
  },
  qrPosterLink: {
    fontSize: 13,
    color: '#475467',
    maxWidth: '100%',
  },
  webModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  webModalCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 16,
    backgroundColor: '#fff',
    padding: 20,
    gap: 16,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  webModalTitle: {
    fontSize: 19,
    fontWeight: '700',
    color: '#111',
  },
  webModalMessage: {
    fontSize: 15,
    color: '#444',
    lineHeight: 21,
  },
  webModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  webModalCancelButton: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#ccc',
    backgroundColor: '#f5f5f5',
  },
  webModalConfirmButton: {
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 10,
    backgroundColor: '#c1121f',
  },
  webModalConfirmButtonDisabled: {
    opacity: 0.6,
  },
  webModalCancelText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#333',
  },
  webModalConfirmText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#fff',
  },
  qrActions: {
    width: '100%',
    marginTop: 4,
  },
  qrShareButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#222',
    alignItems: 'center',
  },
  qrShareText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  qrSaveButton: {
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: '#f5f5f5',
    alignItems: 'center',
  },
  qrSaveText: {
    color: '#111',
    fontSize: 14,
    fontWeight: '600',
  },
  qrButtonDisabled: {
    opacity: 0.7,
  },
});

export default styles;
