import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: '#FAF9FA',
  },
  containerFixed: {
    flex: 1,
  },
  containerContent: {
    paddingHorizontal: 20,
    paddingTop: 16,
    paddingBottom: 32,
    gap: 16,
    flexGrow: 1,
  },
  mobileScroll: {
    flex: 1,
  },
  headerCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    padding: 18,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
    gap: 6,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: '700',
    flex: 1,
  },
  headerTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 2,
  },
  headerEvent: {
    fontSize: 17,
    fontWeight: '600',
    color: '#222',
  },
  headerLine: {
    fontSize: 15,
    color: '#444',
  },
  headerCodeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 8,
  },
  headerCodeValue: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111',
  },
  headerCopyButton: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d0d0d0',
    backgroundColor: '#f5f5f5',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerCopyText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#222',
  },
  statusBadge: {
    fontSize: 13,
    fontWeight: '600',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    overflow: 'hidden',
  },
  statusActive: {
    color: '#0f5132',
    backgroundColor: '#d1e7dd',
  },
  statusClosed: {
    color: '#842029',
    backgroundColor: '#f8d7da',
  },
  connectionText: {
    fontSize: 13,
    color: '#606060',
  },
  posterDivider: {
    height: 1,
    backgroundColor: '#e6e6e6',
    marginTop: 8,
    marginBottom: 12,
  },
  nowServingCard: {
    borderRadius: 14,
    backgroundColor: '#fff',
    borderWidth: 1,
    borderColor: '#dcdcdc',
    padding: 18,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
    gap: 8,
  },
  nowServingHeading: {
    fontSize: 18,
    fontWeight: '700',
  },
  nowServingValue: {
    fontSize: 16,
  },
  timerRow: {
    marginTop: 4,
  },
  timerHint: {
    marginTop: 6,
    fontSize: 13,
    color: '#666',
  },
  queueCard: {
    flexGrow: 1,
    minHeight: 160,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  queueList: {
    flex: 1,
    paddingVertical: 8,
  },
  queueItem: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    gap: 4,
  },
  queueItemLast: {
    borderBottomWidth: 0,
  },
  queueItemName: {
    fontSize: 16,
    fontWeight: '600',
  },
  queueItemMeta: {
    fontSize: 13,
    color: '#606060',
  },
  queueActionsRow: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 16,
  },
  primaryButton: {
    flex: 1,
    backgroundColor: '#111',
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonDisabled: {
    backgroundColor: '#999',
  },
  destructiveButton: {
    flex: 1,
    backgroundColor: '#c1121f',
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  buttonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  queueItemButton: {
    marginTop: 8,
    alignSelf: 'flex-start',
    backgroundColor: '#1f6feb',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 14,
  },
  queueItemButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  emptyState: {
    paddingHorizontal: 20,
    paddingVertical: 18,
  },
  emptyStateText: {
    fontSize: 14,
    color: '#777',
  },
  reconnectButton: {
    marginTop: 6,
    alignSelf: 'flex-start',
    paddingHorizontal: 12,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#bbb',
  },
  reconnectButtonText: {
    fontSize: 14,
    color: '#333',
    fontWeight: '600',
  },
  qrCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    backgroundColor: '#fff',
    padding: 20,
    alignItems: 'center',
    gap: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 1 },
    elevation: 1,
  },
  qrHeading: {
    fontSize: 18,
    fontWeight: '700',
  },
  qrCodeWrapper: {
    padding: 12,
    borderRadius: 12,
    backgroundColor: '#fafafa',
  },
  qrHint: {
    fontSize: 13,
    color: '#606060',
    textAlign: 'center',
  },
  webModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  webModalCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 16,
    backgroundColor: '#fff',
    padding: 20,
    gap: 16,
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 6,
  },
  webModalTitle: {
    fontSize: 19,
    fontWeight: '700',
    color: '#111',
  },
  webModalMessage: {
    fontSize: 15,
    color: '#444',
    lineHeight: 21,
  },
  webModalActions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 12,
  },
  webModalCancelButton: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#ccc',
    backgroundColor: '#f5f5f5',
  },
  webModalConfirmButton: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 14,
    backgroundColor: '#c1121f',
  },
  webModalConfirmButtonDisabled: {
    opacity: 0.6,
  },
  webModalCancelText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#333',
  },
  webModalConfirmText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#fff',
  },
  qrActions: {
    width: '100%',
    marginTop: 4,
  },
  qrShareButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: '#222',
    alignItems: 'center',
  },
  qrShareText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  qrSaveButton: {
    marginTop: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    backgroundColor: '#f5f5f5',
    alignItems: 'center',
  },
  qrSaveText: {
    color: '#111',
    fontSize: 14,
    fontWeight: '600',
  },
  qrButtonDisabled: {
    opacity: 0.7,
  },
  posterCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#e6e6e6',
    backgroundColor: '#fff',
    padding: 20,
    gap: 10,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  posterHeading: {
    fontSize: 18,
    fontWeight: '700',
    color: '#111',
  },
  posterHint: {
    fontSize: 13,
    color: '#555',
    lineHeight: 18,
  },
  posterHintMuted: {
    fontSize: 13,
    color: '#888',
  },
  posterButtons: {
    flexDirection: 'row',
    gap: 12,
    width: '100%',
    flexWrap: 'wrap',
    marginTop: 12,
  },
  posterButton: {
    flex: 1,
    minWidth: 160,
    backgroundColor: '#111',
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
  },
  posterButtonSecondary: {
    flex: 1,
    minWidth: 160,
    backgroundColor: '#f5f5f5',
    paddingVertical: 12,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#d0d0d0',
    flexDirection: 'row',
    gap: 8,
  },
  posterButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
  posterButtonSecondaryText: {
    color: '#111',
    fontSize: 14,
    fontWeight: '600',
  },
  posterButtonDisabled: {
    opacity: 0.65,
  },
  posterModalBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  posterModalCard: {
    width: '100%',
    maxWidth: 600,
    maxHeight: '95%',
    borderRadius: 16,
    backgroundColor: '#fff',
    shadowColor: '#000',
    shadowOpacity: 0.25,
    shadowRadius: 20,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
    overflow: 'hidden',
  },
  posterModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#e6e6e6',
  },
  posterModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#111',
  },
  posterModalCloseButton: {
    padding: 4,
    borderRadius: 8,
  },
  posterModalLoading: {
    padding: 60,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 16,
  },
  posterModalLoadingText: {
    fontSize: 15,
    color: '#666',
  },
  posterModalImageContainer: {
    flex: 1,
    maxHeight: 700,
  },
  posterModalImageContent: {
    alignItems: 'center',
    justifyContent: 'center',
    padding: 20,
    minHeight: '100%',
  },
  posterModalImageWrapper: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  posterModalImage: {
    width: '100%',
    aspectRatio: 1080 / 1920,
    maxWidth: '100%',
    maxHeight: 660,
    borderRadius: 8,
  },
  posterModalImagePlaceholder: {
    fontSize: 14,
    color: '#999',
    padding: 40,
  },
  posterModalControls: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderTopWidth: 1,
    borderTopColor: '#e6e6e6',
    gap: 16,
  },
  posterModalCheckboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  posterModalCheckbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#ccc',
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
  posterModalCheckboxChecked: {
    backgroundColor: '#111',
    borderColor: '#111',
  },
  posterModalCheckboxLabel: {
    fontSize: 15,
    color: '#333',
    fontWeight: '500',
  },
  posterModalDownloadButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#111',
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 14,
  },
  posterModalDownloadText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: '600',
  },
});

export default styles;
